### ISSUE TITLE
Support different package manager

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/credits#3]
As discussed here it should be possible to analyse different systems.

https://github.com/stefanjudis/credits-cli/issues/9
- [ ] add support for bower
- [ ] add support for jspm

**Comment by radibit** [comment]
@stefanjudis 

I just finished a major code refactoring with the [following commit](https://github.com/stefanjudis/credits/commit/2ff9ec787fdbd412e9b6593ddd6d9a75e9120414) in order to achieve better structure for different package managers. Tests are also updated.

I will be glad if you give me a CR before I move to `bower` and `jspm`, just to be sure I'm in the right direction. Of course I'm also open for further improvements :smiley: 

Thanks!

**Comment by stefanjudis** [comment]
we can have a look tomorrow. :)

**Comment by Hypercubed** [comment]
Love to see some of this merged.  I've been using a hacked version for a while now: https://github.com/Hypercubed/Project-Chi/blob/master/credits.md

**Comment by Hypercubed** [comment]
Hi @stefanjudis, do you need help with this repo?

**Comment by stefanjudis** [comment]
@Hypercubed oh yeah...

Are you up for becoming a collab? I'd love to have another person on board. 🎉

**Comment by Hypercubed** [comment]
Yes....  👍

**Comment by stefanjudis** [comment]
Invite sent. :D 

Happy to have you onboard. 🎉 

I'd like to stick to a PR flow here and in case you need anything - make sure to ping me with `@stefanjudis`.

**Comment by Hypercubed** [comment]
I might need access to credits-cli as well. I7m not sure what to do with all the greenkeeper PRs.

**Comment by stefanjudis** [comment]
> I might need access to credits-cli as well. 

Will give you in 2min.

About the greenkeeper PR's. You drop them. :D Wouldn't spent to much time with them. Maybe you've got time to have a look a dep updates, which would be great.

For the future including `semantic release` would be awesome.
